name: Serve JSON Server

on:
  push:
    branches:
      - main

jobs:
  serve:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm ci
      - name: Start JSON Server
        run: npm run start
        timeout-minutes: 10